FireTwoDotZero/src/main/java/se/gu/fire/backend/AssignmentBean.java
package se.gu.fire.backend;

import com.google.common.base.Strings;
import java.io.ByteArrayInputStream;
import java.util.Collections;
import java.util.Comparator;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import se.gu.fire.core.Assignment;
import se.gu.fire.core.Comment;
import se.gu.fire.core.FireUser;
import se.gu.fire.core.StoredFile;
import se.gu.fire.core.StudentGroup;
import se.gu.fire.core.Submission;
import se.gu.fire.core.Submission.SubmissionStatus;
import se.gu.fire.data.inter.IAssignmentManager;
import se.gu.fire.data.inter.IGroupManager;
import se.gu.fire.data.SubmissionManager;
import se.gu.fire.data.UserManager;
import se.gu.fire.util.FireUtil;

/**
 * Handles the assignment page where users se information about one assignment
 * for one group. Files can be downloaded and comments made.
 */
// NOTE: Using faces managed bean here, to be able to use ViewScope.
@ViewScoped
@ManagedBean(name = "assignBean")
public class AssignmentBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Assignment assign;

    // Map from assign id to value of new comment textbox
    private Map<Long, String> newCommentMap = new LinkedHashMap<>();

    private Long assignId;

    private String activeSubPanels;

    private SubmissionStatus assignStatus;
    private List<Submission> subs;
    private FireUser user;
    private StudentGroup group;

    @EJB
    private IAssignmentManager assignMan;

    @EJB
    private SubmissionManager subMan;

    @EJB
    private IGroupManager groupMan;

    @EJB
    private UserManager userMan;

    public void viewParamChanged(ValueChangeEvent ev) {
        // Sometimes value is string, sometimes long? TODO: Seems like always long?
        long parseLong = Long.parseLong((String)ev.getNewValue().toString());
        
        assign = assignMan.read(parseLong);
        user = userMan.findUser(FireUtil.getLoggedinUserEmail());
        group = groupMan.getGroupForUser(user);
        assignStatus = subMan.getAssignmentStatus(assign, group);
        subs = subMan.getAllByGroup(assign, group);

        Collections.sort(subs, new Comparator<Submission>() {
            @Override public int compare(Submission s1, Submission s2) {
                return s1.getSubmitTime().compareTo(s2.getSubmitTime());
            }
        });

        activeSubPanels = Integer.toString(subs.size() - 1);
    }

    public StreamedContent download(StoredFile file) {
        return new DefaultStreamedContent(
                        new ByteArrayInputStream(file.getFileData()),
                        file.getContentType(),
                        file.getFileName());
    }

    public StreamedContent downloadAll(Submission sub) {
        String filename = sub.getAssignment().getTitle().replace(' ', '_')
                + "_group_" + sub.getSubmittingGroup().getId() + "_all_files.zip";

        return new DefaultStreamedContent(
                        FireUtil.zipFiles(sub.getFiles()),
                        "application/zip", filename);
    }

    public Long getAssignId() {
        return assignId;
    }

    public void setAssignId(Long assignId) {
        this.assignId = assignId;
    }

    public void submitComment(Submission sub) {
        String text = newCommentMap.get(sub.getId());

        if (Strings.isNullOrEmpty(text)) {
            FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Empty comments not allowed", null));
            return;
        }

        sub.addComments(new Comment(user, newCommentMap.get(sub.getId())));
        subMan.update(sub);
        getNewCommentMap().remove(sub.getId());
    }

    public SubmissionStatus getAssignmentStatus() {
        return assignStatus;
    }

    public List<Submission> getSubmissions() {
        return  subs;
    }

    public Assignment getAssign() {
        return assign;
    }

    public StudentGroup getGroup() {
        return group;
    }

    public Map<Long, String> getNewCommentMap() {
        return newCommentMap;
    }

    public String getActiveSubPanels() {
        return activeSubPanels;
    }

    public void setActiveSubPanels(String activeSubPanels) {
        this.activeSubPanels = activeSubPanels;
    }
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/AssignmentListBean.java
package se.gu.fire.backend;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import se.gu.fire.core.Assignment;
import se.gu.fire.core.FireUser;
import se.gu.fire.core.StudentGroup;
import se.gu.fire.data.inter.IAssignmentManager;
import se.gu.fire.data.inter.IGroupManager;
import se.gu.fire.data.inter.ISubmissionManager;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.util.FireUtil;

/**
 * Displays as list of assignments and the overall status of each. Mostly used
 * to navigate to the assignment page.
 */
@Named(value = "assignListBean")
@SessionScoped
public class AssignmentListBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@EJB
    private IAssignmentManager assignMan;
    @EJB
    private ISubmissionManager subMan;
    @EJB
    private IGroupManager groupMan;
    @EJB
    private IUserManager userMan;

    private FireUser activeUser;
    private StudentGroup group;

    public AssignmentListBean() {
    }

    @PostConstruct
    public void init() {
        activeUser = userMan.findUser(FireUtil.getLoggedinUserEmail());
        group = groupMan.getGroupForUser(activeUser);
    }

    public List<Assignment> getAssignments() {
        return assignMan.getAll();
    }

    public String getStatus(String assignIdStr) {
        if (group == null) {
            return "No group";
        }
        return subMan.getAssignmentStatus(assignMan.read(Long.parseLong(assignIdStr)), group).toString();
    }
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/BeginPasswordResetBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.gu.fire.backend;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.mail.MessagingException;
import se.gu.fire.backend.constraints.EmailConstraint;
import se.gu.fire.backend.intersession.InterSessionContextBean;
import se.gu.fire.core.FireUser;
import se.gu.fire.data.UserManager;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.mail.Mailer;
import se.gu.fire.util.FireFaces;
import se.gu.fire.util.FireLogger;

@Named("beginPasswordResetBean")
@RequestScoped
public class BeginPasswordResetBean implements Serializable {
    private static final long serialVersionUID = 1L;

    @Inject
    private InterSessionContextBean interSessionContextBean;
    @EJB
    private IUserManager userManager;
    
    @EmailConstraint
    private String userEmail;
    
    /**
     * Send an email to the user, containing his/her password
     */
    public void beginPasswordReset() {
        FireLogger.logInfo("Attempting to reset password for user: {0}", userEmail);

        if (userEmail == null) {
            FireFaces.addErrorMessage("Email not found in system {0}", userEmail);
        }

        FireUser targetUser = userManager.findUser(userEmail);

        if (targetUser == null) {
            FireLogger.logInfo("Could not find email: {0}", userEmail);
            FireFaces.addWarningMessage("Email not found in system");
            return;
        }

        String sessionKey = interSessionContextBean.addPasswordRecoverySessionData(userEmail);

        StringBuilder toSend = new StringBuilder()
                .append("Hello there ")
                .append(targetUser.getFullName())
                .append("!\n\nPlease follow this url in order to reset your password for the Fire system:\n\nlocalhost:8080/PrimeFire/faces/resetPassword.xhtml?sessionKey=")
                .append(sessionKey)
                .append("\n\nhugs,\n\nthe Fire team");

        try {
            Mailer.send(userEmail, "Fire: reset password", toSend.toString());
        }
        catch (MessagingException ex) {
            FireLogger.logSevere("unable to send mail to user {0}", userEmail);
            FireFaces.addErrorMessage("Unable to send email", ex.getMessage());
            return;
        }

        FireLogger.logInfo("Sent password reset instructions to: {0}", userEmail);
        FireFaces.addInfoMessage("A mail has been sent with instructions on resetting your password");
    }
    
    public InterSessionContextBean getInterSessionContextBean() {
        return interSessionContextBean;
    }

    public void setInterSessionContextBean(InterSessionContextBean interSessionContextBean) {
        this.interSessionContextBean = interSessionContextBean;
    }

    public IUserManager getUserManager() {
        return userManager;
    }

    public void setUserManager(UserManager userManager) {
        this.userManager = userManager;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/ContactBean.java
package se.gu.fire.backend;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.mail.MessagingException;
import se.gu.fire.mail.Mailer;
import se.gu.fire.util.FireFaces;
import se.gu.fire.util.FireLogger;
import se.gu.fire.util.FireUtil;

/**
 * Used for collecting contact information from a client, and sending it back to
 * the developers.
 */
@Named("contactBean")
@RequestScoped
public class ContactBean {

    private String message = "";

    public ContactBean() {
        FireLogger.logInfo("Created ContactBean for user {0}", FireUtil.getLoggedinUserEmail());
    }

    public String doSend() {

        if (message.isEmpty()) {
            FireFaces.addErrorMessage("Your message is empty!");
            return "";
        }

        String email = FireUtil.getLoggedinUserEmail();

        StringBuilder toSend = new StringBuilder();
        toSend.append("You have received feedback from Fire.\n\n")
                .append("From user: ")
                .append(FireUtil.getLoggedinUserEmail())
                .append("\n\nFeedback: ")
                .append(message);
        
        try {
            Mailer.send(email, "Fire: new feedback received", toSend.toString());
        }
        catch (MessagingException ex) {
            FireLogger.logSevere("unable to send mail to user {0}", email);
            FireFaces.addErrorMessage("Unable to send email", ex.getMessage());
            return "";
        }
        FireLogger.logInfo("User feedback from {0} has been sent!", email);
        return "index?faces-redirect=true";
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/SettingsBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.gu.fire.backend;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import se.gu.fire.core.FireUser;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.util.FireLogger;
import se.gu.fire.util.FireUtil;

@Named("settingsBean")
@RequestScoped
public class SettingsBean {
    
    private FireUser user;
    
    @EJB
    private IUserManager userManager;
    
    public SettingsBean() {
        FireLogger.logInfo("Creating new UserSettingsBean for user {0}", FireUtil.getLoggedinUserEmail());
    }
    
    @PostConstruct
    public void fetchUser() {
        user = userManager.findUser(FireUtil.getLoggedinUserEmail());
    }
    
    public void performUpdate() {
        userManager.update(user);
    }
    
    public String getEmail() {
        return user.getEmail();
    }

    public void setEmail(String email) {
        user.setEmail(email);
    }

    public String getFname() {
        return user.getFname();
    }

    public void setFname(String fname) {
        user.setFname(fname);
    }

    public String getLname() {
        return user.getLname();
    }

    public void setLname(String lname) {
        user.setLname(lname);
    }
    
    public String getFullName() {
        return user.getFullName();
    }
    
    public String getPersonalNumber() {
        return user.getPersonnummer();
    }

    /*
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    */
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/SubmissionBean.java
package se.gu.fire.backend;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import se.gu.fire.core.Assignment;
import se.gu.fire.core.FireUser;
import se.gu.fire.core.StoredFile;
import se.gu.fire.core.StudentGroup;
import se.gu.fire.core.Submission;
import se.gu.fire.data.inter.IAssignmentManager;
import se.gu.fire.data.inter.IGroupManager;
import se.gu.fire.data.inter.ISubmissionManager;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.util.FireLogger;
import se.gu.fire.util.FireUtil;

/**
 * Handles the submission page. Uploading of files. Creation of a new
 * Submission.
 */
@ManagedBean(name = "subBean")
@ViewScoped
public class SubmissionBean {


    private Long assignId;

    private Assignment assign;
    private List<Submission> subs;
    private FireUser user;
    private StudentGroup group;

    private String blockReason;

    private List<UploadedFile> uploadedFiles = new ArrayList<>();

    @EJB
    private IAssignmentManager assignMan;

    @EJB
    private ISubmissionManager subMan;

    @EJB
    private IGroupManager groupMan;

    @EJB
    private IUserManager userMan;

    public void viewParamChanged(ValueChangeEvent ev){
        // Sometimes value is string, sometimes long? TODO: Seems like always long?
        long parseLong = Long.parseLong((String)ev.getNewValue().toString());

        FireLogger.logInfo("View param changed: {0} Class: {1}", ev.getNewValue(), ev.getNewValue().getClass());

        assign = assignMan.read(parseLong);
        user = userMan.findUser(FireUtil.getLoggedinUserEmail());
        group = groupMan.getGroupForUser(user);
        subs = subMan.getAllByGroup(assign, group);

        blockReason = FireUtil.calcBlockStatus(assign, subs, new Date());

        FireLogger.logInfo("blockReason: " + blockReason);
    }

    public void handleFileUpload(FileUploadEvent event) {
        FireLogger.logInfo("handleFileUpload: {0}", event.toString());

        for (UploadedFile file : getUploadedFiles()) {
            if (event.getFile().getFileName().equals(file.getFileName())) {
                FacesContext.getCurrentInstance().addMessage(null,
                        new FacesMessage(FacesMessage.SEVERITY_ERROR,
                            "Duplicate filenames not allowed", null));
                return;
            }
        }

        getUploadedFiles().add(event.getFile());
        FacesMessage msg = new FacesMessage(event.getFile().getFileName() + " is uploaded.", null);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }


    public List<UploadedFile> getUploadedFiles() {
        return uploadedFiles;
    }

    public String submit() {

        if (uploadedFiles.isEmpty()) {
                FacesContext.getCurrentInstance().addMessage(null,
                        new FacesMessage(FacesMessage.SEVERITY_ERROR,
                            "Submission not allowed because no files are uploaded.", null));
                return null;
        }

        Submission sub = new Submission.Builder()
                .assignment(assign)
                .submittingGroup(group)
                .build();

        for (UploadedFile file : getUploadedFiles()) {
            sub.addFile(new StoredFile(file.getFileName(),
                    file.getContents(), file.getContentType()));
        }

        FireLogger.logInfo(uploadedFiles.toString());

        subMan.create(sub);

        clearUploadedFiles();

        return "submitConfirmation?faces-redirect=true";
    }

    public void clearUploadedFiles() {
        getUploadedFiles().clear();
    }

    public void deleteFile(UploadedFile file) {
        getUploadedFiles().remove(file);
    }

    public Long getAssignId() {
        return assignId;
    }

    public void setAssignId(Long assignId) {
        this.assignId = assignId;
    }

    public Assignment getAssignment() {
        return assign;
    }

    public String getBlockReason() {
        return blockReason;
    }

    public boolean isSubissionAllowed() {
        return blockReason == null;
    }


}

FireTwoDotZero/src/main/webapp/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./templates/fireLeftMenuTemplate.xhtml">

            <ui:define name="left">
                <p:menu>
                    <p:submenu label="Course settings">
                        
                    </p:submenu>
                    <p:submenu label="Lab setting">
                        
                    </p:submenu>
                    <p:submenu label="Grader settings">
                        
                    </p:submenu>
                    
                    <p:submenu label="Assignment settings" >
                        <p:menuitem value="Create Assignment " outcome="#{navigation.navigateTo('createAssignment')}" icon="ui-icon-lightbulb"/>         
                    </p:submenu>

                </p:menu>
            </ui:define>

            <ui:define name="content">
                content
            </ui:define>

        </ui:composition>

    </body>
</html>

FireTwoDotZero/src/main/webapp/assignmentList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:body>

        <ui:composition template="./templates/fireTemplate.xhtml">

            <ui:define name="content">

                    <p:panel header="Assignments" styleClass="light2" >
                        <h:form>
                            <p:dataTable var="assign" value="#{assignListBean.assignments}" >
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Title"/>
                                    </f:facet>
                                    <h:link value="#{assign.title}"
                                            outcome="assignment"
                                            includeViewParams="true">
                                        <!-- User view params to send ID to outcome page -->
                                        <f:param name="assignId" value="#{assign.id}"/>
                                    </h:link>
                                </p:column>

                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText  value="Description"/>
                                    </f:facet>
                                    <h:outputText value="#{assign.information}"/>
                                </p:column>

                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText  value="Status"/>
                                    </f:facet>
                                    <h:outputText value="#{assignListBean.getStatus(assign.id)}"/>
                                </p:column>

                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText  value="Next deadline"/>
                                    </f:facet>
                                    <h:outputText value="#{assign.nextDeadline}"/>
                                </p:column>

                            </p:dataTable>
                        </h:form>
                    </p:panel>
                    
                </ui:define>

        </ui:composition>
    </h:body>
</html>

FireTwoDotZero/src/main/webapp/confirmRegistration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <f:event type="preRenderView" listener="#{confirmRegistrationBean.doFinishRegistration()}"/>
    </f:view>

    <h:head>
        <title>Fire - Registration</title>
    </h:head>

    <h:body>
        <h:form>
            <p:panel>
                <p:messages autoUpdate="true"/>
            </p:panel>
        </h:form>
    </h:body>
</html>

FireTwoDotZero/src/main/webapp/contact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:body>

        <ui:composition template="./templates/fireTemplate.xhtml">

            <ui:define name="content">

                <p:growl id="growl" showDetail="true" life="5000" />

                <h:form>

                    <p:panel header="Contact us">

                        <h:panelGrid columns="2" cellpadding="5" id="contactGrid">

                        </h:panelGrid>

                        <p:panel styleClass="light">

                            <div style="margin: 0px 20px 20px 20px;">
                                Whats on your mind?
                            </div>

                            <div style="margin: 20px 20px 20px 20px">
                                <p:inputTextarea id="message" 
                                                 value="#{contactBean.message}" 
                                                 rows="20" 
                                                 cols="32" 
                                                 autoResize="false"/>
                            </div>

                        </p:panel>
                        
                         <p:commandButton id="sendButton" 
                                     value="send" 
                                     action="#{contactBean.doSend()}"
                                     update=":growl"/>

                    </p:panel>

                   

                </h:form>

            </ui:define>

        </ui:composition>

    </h:body>

</html>

FireTwoDotZero/src/main/webapp/grading.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <body>

        <ui:composition template="./templates/fireLeftMenuTemplate.xhtml">

            <ui:define name="left">
                <h:form>
                    <p:menu model="#{gradingBean.courseMenu}"/>
                </h:form>
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <p:accordionPanel value="#{gradingBean.populateAccordion()}" var="submission">
                        <p:tab title="#{submission.submittingGroup}"/>
                        <p:commandButton value="Accept" action="#}" />
                    </p:accordionPanel>         
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

FireTwoDotZero/src/main/webapp/settings.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./templates/fireTemplate.xhtml">

            <ui:define name="content">

                <p:growl id="growl" showDetail="true" life="5000" />

                <h:form>

                    <p:panel header="Account overview">

                        <p:panel styleClass="light">

                            <!-- Personal details -->
                            <h:outputText value="Personal details" styleClass="light_header"/>

                            <h:panelGrid columns="1" styleClass="light_text">
                                <h:outputText value="Name: #{settingsBean.fullName}"/>
                                <h:outputText value="Personal number: #{settingsBean.personalNumber}"/>
                            </h:panelGrid>

                            <!-- Password Settings -->
                            <h:outputText value="Password settings" styleClass="light_header"/>

                                <h:panelGrid columns="1" styleClass="light_text">

                                    <p:commandLink id="passwordOverlayRenderer" value="reset password"/>

                                    <!-- Overlay panel for showing the password reset stuff-->
                                    <p:overlayPanel id="carPanel" for="passwordOverlayRenderer" hideEffect="fade" showEffect="fade" dynamic="true">  

                                        <p:panel header="Select your new password">

                                            <h:panelGrid columns="2" cellpadding="5" id="resetPasswordGrid">

                                                <p:outputLabel for="newPassword" value="Type your new password"/>
                                                <p:password id="newPassword" 
                                                            value="#{seetingsResetPasswordBean.firstPassword}"
                                                            feedback="true"/>

                                                <p:outputLabel for="retypedPassword" value="Retype your password"/>
                                                <p:password id="retypedPassword" 
                                                            value="#{seetingsResetPasswordBean.secondPassword}"/>

                                            </h:panelGrid>

                                            <p:commandButton id="confirmButton" 
                                                             value="reset password" 
                                                             action="#{seetingsResetPasswordBean.doResetPassword()}"
                                                             update=":growl"/>

                                        </p:panel> 

                                    </p:overlayPanel>  

                                </h:panelGrid>

                            <!-- Email settings -->
                            <h:outputText value="Email settings" styleClass="light_header"/>

                            <h:panelGrid columns="1" styleClass="light_text">

                            </h:panelGrid>

                        </p:panel>

                    </p:panel>

                </h:form>

            </ui:define>

        </ui:composition>

    </body>
</html>

FireTwoDotZero/src/main/webapp/submission.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

<f:metadata>
    <f:viewParam name="assignId" value="#{subBean.assignId}"
                 valueChangeListener="#{subBean.viewParamChanged}" />
</f:metadata>

<h:body>
<ui:composition template="./templates/fireTemplate.xhtml">
<ui:define name="content">

<p:growl sticky="true" autoUpdate="true"/>

<p:panel header="Submission - #{subBean.assignment.title}">

    <!-- Show error message -->
    <c:if test="#{not subBean.subissionAllowed}">
        <h:outputText value="It is not possible to make a submission."/>
        <br/>
        <br/>
        <h:outputText value="#{subBean.blockReason}."/>
        <br/>
        <br/>
    </c:if>

    <c:if test="#{subBean.subissionAllowed}">
        <!-- Show submission page if sub is allowd -->
        <h:form enctype="multipart/form-data">

            <h:outputText value="No files uploaded"
                          rendered="#{empty subBean.uploadedFiles}" />

            <p:dataList var="file" value="#{subBean.uploadedFiles}"
                        id="fileList" type="definition"
                        rendered="#{not empty subBean.uploadedFiles}">

                <h:outputText value="#{file.fileName}  " />
                <p:commandButton icon="ui-icon-circle-close"
                                 process="@form"
                                 actionListener="#{subBean.deleteFile(file)}"
                                 update="@form" />
            </p:dataList>
            <br/>

            <p:commandButton value="Clear" actionListener="#{subBean.clearUploadedFiles()}"
                             update="fileList"/>
            <br/>
            <br/>

            <p:commandButton value="Submit"
                             action="#{subBean.submit()}" />
            <br/>
            <br/>

            <p:fileUpload fileUploadListener="#{subBean.handleFileUpload}"
                          showButtons="true"
                          mode="advanced"
                          update="@form"
                          multiple="true"
                          sizeLimit="100000"
                    />

        </h:form>
    </c:if>

</p:panel>



</ui:define>
</ui:composition>
</h:body>
</html>