FireTwoDotZero/src/main/java/se/gu/fire/backend/SettingsBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se.gu.fire.backend;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import se.gu.fire.core.FireUser;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.util.FireLogger;
import se.gu.fire.util.FireUtil;

@Named("settingsBean")
@RequestScoped
public class SettingsBean {
    
    private FireUser user;
    
    @EJB
    private IUserManager userManager;
    
    public SettingsBean() {
        FireLogger.logInfo("Creating new UserSettingsBean for user {0}", FireUtil.getLoggedinUserEmail());
    }
    
    @PostConstruct
    public void fetchUser() {
        user = userManager.findUser(FireUtil.getLoggedinUserEmail());
    }
    
    public void performUpdate() {
        userManager.update(user);
    }
    
    public String getEmail() {
        return user.getEmail();
    }

    public void setEmail(String email) {
        user.setEmail(email);
    }

    public String getFname() {
        return user.getFname();
    }

    public void setFname(String fname) {
        user.setFname(fname);
    }

    public String getLname() {
        return user.getLname();
    }

    public void setLname(String lname) {
        user.setLname(lname);
    }
    
    public String getFullName() {
        return user.getFullName();
    }
    
    public String getPersonalNumber() {
        return user.getPersonnummer();
    }

    /*
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    */
}

FireTwoDotZero/src/main/java/se/gu/fire/backend/TemplateBean.java
package se.gu.fire.backend;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import se.gu.fire.core.FireUser;
import se.gu.fire.data.inter.IUserManager;
import se.gu.fire.util.FireUtil;

@RequestScoped
@Named("templateBean")
public class TemplateBean {
    @EJB
    private IUserManager userMan;

    public FireUser getActiveUser() {
        return userMan.findUser(FireUtil.getLoggedinUserEmail());
    }
}

FireTwoDotZero/src/main/webapp/templates/fireFooter.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:s="http://shiro.apache.org/tags">

    <h:body>
        
        <ui:composition>
            
            <h:panelGrid columns="2" class="navigation_table">
                
                <h:outputLabel value="Brought to you by the Fire team"/>
                
                <s:authenticated>
                    <h:link value="Send us your feedback!" outcome="contact"/>
                </s:authenticated>  
                
            </h:panelGrid>
            
        </ui:composition>     
        
    </h:body>
</html>

FireTwoDotZero/src/main/webapp/templates/fireHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://shiro.apache.org/tags"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:body>
        
        <ui:composition>

            <s:authenticated>

                <h:form>
                    <p:tabMenu activeIndex="#{navigation.tab}">

                        <p:menuitem value="Home" action="#{navigation.navigateTo('index')}" icon="ui-icon-home"/>
                        <p:menuitem value="Assignments" action="#{navigation.navigateTo('assignmentList')}" icon="ui-icon-lightbulb"/>
                        <p:menuitem value="Grading" action="#{navigation.navigateTo('grading')}" icon="ui-icon-lightbulb"/>
                        <p:menuitem value="Groups" action="#{navigation.navigateTo('groups')}" icon="ui-icon-person"/>
                        <p:menuitem value="Account" action="#{navigation.navigateTo('settings')}" icon="ui-icon-gear"/>
                        <p:menuitem value="Help" action="#{navigation.navigateTo('help')}" icon="ui-icon-help"/>
                        
                        <s:hasRole name="ADMIN">
                            <p:menuitem value="Test" action="#{navigation.navigateTo('test')}" icon="ui-icon-script"/>
                            <p:menuitem value="Administration" action="#{navigation.navigateTo('admin')}" icon="ui-icon-locked"/>
                        </s:hasRole>

                    </p:tabMenu>

                </h:form>

                <div style="position: absolute; top: 5px; right: 20px;">
                    <h:form>
                        <p:menuButton value="#{templateBean.activeUser.fullName}">
                            <p:menuitem value="Account settings" outcome="settings" icon="ui-icon-person"/>
                            <p:separator/>
                            <p:menuitem value="Logout" action="#{logoutBean.doLogout()}"/>
                        </p:menuButton>
                    </h:form>
                </div>

            </s:authenticated>

        </ui:composition>

    </h:body>
    
</html>

FireTwoDotZero/src/main/webapp/templates/fireLeftMenuTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <h:outputStylesheet name="cssLayout.css" library="css" />
        <h:outputStylesheet name="default.css" library="css" />
        <title>Fire!</title>
    </h:head>

    <h:body>

            <div id="top">
                <ui:include src="fireHeader.xhtml"/>
            </div>

            <div style="margin: 40px 100px 40px 10px">
                <h:panelGrid columns="2" cellpadding="20px">

                    <ui:insert name="left"></ui:insert>

                    <ui:insert name="content"></ui:insert>

                </h:panelGrid>
            </div>

            <div id="bottom">
                <ui:include src="fireFooter.xhtml"/>
            </div>
            
    </h:body>

</html>

FireTwoDotZero/src/main/webapp/templates/fireTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <h:outputStylesheet name="cssLayout.css" library="css" />
        <h:outputStylesheet name="default.css" library="css" />
        <title>Fire!</title>
    </h:head>

    <h:body>
        
        <div id="page">
            
            <div id="top">
                <ui:include src="fireHeader.xhtml"/>
            </div>
            
                <div id="content" class="center_content">
                    <ui:insert name="content"></ui:insert>
                </div>
          
<!--            TODO: This hovers over my text instead of sitting at the bottom-->
           <div id="bottom">
                <ui:include src="fireFooter.xhtml"/>
            </div>
            
        </div>
    </h:body>

</html>